import mongoose from "mongoose";

const BenhNhanSchema = mongoose.Schema({
    ngayKhamBenh: String,
    thoiGianPhatHien: String,
    maBenhNhan: String,
    tienSuAnhChi: String,
    tienSuBoMe: String,
    tanSuatKham: String,
    diaChi: String,
    dungSmartPhone: String,
    trinDoHocVan: String,
    gioiTinh: String,
    tuoi: Number,
    ten: String,
    hba1cLucDau: String,
    benhKemTheo: String,
    tienSuBenh: [String],
    dieuTriDTD: String,
    thoigianM1: String,
    dieuTriTHA: String,
    thoigianM2: String,
    nhomThuocTS: [String],
    thuocHaApTS: [String],
    haMoMauTS: [String],
    chieuCao: String,
    canNang: String,
    BMI: String,
    HATT: String,
    HATTr: String,
    nhomThuoc: [String],
    thuocHaAp: [String],
    haMoMau: [String],
    Hb: String,
    Hema: String,
    HbA: String,
    Glu: String,
    Ure: String,
    Creatinin: String,
    eGFR: String,
    Cholesterol: String,
    LDLC: String,
    HDLC: String,
    Trigly: String,
    Na: String,
    K: String,
    Ca: String,
    sieuAm: String,
    khamMat: String,
    nuoctieu_albumin: String,
    ghiChu: String,
    soNamDTD: String
}, {
    collection: "note"
});

export default mongoose.model("BenhNhan", BenhNhanSchema);
